# vim:ft=kitty

# ---- Font ----
font_family JetBrains Mono
bold_font auto
font_size 17

# ---- Cursor ----
cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 5.0
cursor_text_color #121212
cursor #8F9F7B
cursor_trail 0

# ---- Transparency ----
background_opacity 0.75
dynamic_background_opacity yes

# ---- Window ----
window_border_width 1
active_border_color #7E8B6B
inactive_border_color #2A2A2A
window_padding_width 8

# ---- Base colors ----
foreground #C0C0C0
background #121212

selection_foreground none
selection_background #2A2A2A

# ---- URL / tabs ----
url_color #8F9F7B
active_tab_foreground #D0D0D0
active_tab_background #121212
inactive_tab_foreground #7A7A7A
inactive_tab_background #121212

# ---- ANSI colors ----

# black / paper
color0  #121212
color8  #3A3A3A

# red 
color1  #5C5C5C
color9  #6A6A6A

# green 
color2  #8F9F7B
color10 #7E8B6B

# yellow 
color3  #8A846A
color11 #9A9478

# blue 
color4  #6A6A6A
color12 #7A7A7A

# magenta 
color5  #9A9A9A
color13 #AAAAAA

# cyan 
color6  #7E8E84
color14 #8FA09A

# white / highlight
color7  #B0B0B0
color15 #D0D0D0

# ---- Underlines ----
underline_color #7E8B6B

# BINDS
map alt+j previous_tab
map alt+k next_tab
map alt+t new_tab
map alt+c close_tab
map alt+shift+t new_tab_with_cwd
