wallpaper {
    monitor = DP-5
    path = ~/Pictures/Wallpapers/black_and_white_mountains.jpg
}

wallpaper {
    monitor = DP-6
    path = ~/Pictures/Wallpapers/black_and_white_mountains.jpg
}

wallpaper {
    monitor = HDMI-A_1
    path= ~/Pictures/Wallpapers/black_and_white_mountains.jpg
    }

ipc = true
splash = false
